#!/usr/bin/env python3
"""Generate compact Unicode 3.2 range tables for RFC 4013 SASLprep."""

from pathlib import Path
import hashlib
import stringprep

MAX_CODE_POINT = 0x10FFFF


def ranges(predicate):
    result = []
    start = None
    previous = None
    for code_point in range(MAX_CODE_POINT + 1):
        if predicate(chr(code_point)):
            if start is None:
                start = code_point
            previous = code_point
        elif start is not None:
            result.extend((start, previous))
            start = None
    if start is not None:
        result.extend((start, previous))
    return result


def union(*predicates):
    return lambda char: any(predicate(char) for predicate in predicates)


TABLES = {
    "MAP_TO_NOTHING": ranges(stringprep.in_table_b1),
    "NON_ASCII_SPACE": ranges(stringprep.in_table_c12),
    "PROHIBITED": ranges(
        union(
            stringprep.in_table_c21,
            stringprep.in_table_c22,
            stringprep.in_table_c3,
            stringprep.in_table_c4,
            stringprep.in_table_c5,
            stringprep.in_table_c6,
            stringprep.in_table_c7,
            stringprep.in_table_c8,
            stringprep.in_table_c9,
        )
    ),
    "UNASSIGNED": ranges(stringprep.in_table_a1),
    "RANDAL": ranges(stringprep.in_table_d1),
    "LCAT": ranges(stringprep.in_table_d2),
}


def format_values(values):
    lines = []
    for index in range(0, len(values), 12):
        line = ", ".join(f"0x{value:x}" for value in values[index:index + 12])
        lines.append(f"  {line}")
    return ",\n".join(lines)


source = [
    "/* Generated by scripts/generate-saslprep-tables.py.",
    " * Source: Python stringprep (RFC 3454 / Unicode 3.2 tables).",
    " * Do not edit by hand.",
    " */",
    "",
]
for name, values in TABLES.items():
    source.extend(
        [
            f"export const {name}: readonly number[] = [",
            format_values(values),
            "];",
            "",
        ]
    )

body = "\n".join(source)
checksum = hashlib.sha256(body.encode()).hexdigest()
body = body.replace(
    " * Do not edit by hand.",
    f" * SHA-256 of generated body before this checksum: {checksum}\n * Do not edit by hand.",
)
target = Path(__file__).resolve().parents[1] / "src/encryption/saslprep-tables.ts"
target.write_text(body)
print(target)
