import type { PDFDocument, PDFFont, PDFImage } from "pdf-lib";

export type AssetSource = string | Uint8Array | ArrayBuffer;

const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47];
const JPEG_MAGIC = [0xff, 0xd8, 0xff];

function bytesStartWith(bytes: Uint8Array, magic: number[]): boolean {
  if (bytes.length < magic.length) return false;
  for (let i = 0; i < magic.length; i += 1) {
    if (bytes[i] !== magic[i]) return false;
  }
  return true;
}

async function readSource(source: AssetSource): Promise<Uint8Array> {
  if (source instanceof Uint8Array) return source;
  if (source instanceof ArrayBuffer) return new Uint8Array(source);
  if (typeof source === "string") {
    // 1) data: URLs are parsed inline.
    if (source.startsWith("data:")) {
      const comma = source.indexOf(",");
      if (comma === -1) throw new Error("Malformed data URL");
      const header = source.slice(5, comma);
      const payload = source.slice(comma + 1);
      if (header.includes(";base64")) {
        return decodeBase64(payload);
      }
      return new TextEncoder().encode(decodeURIComponent(payload));
    }
    // 2) http(s)/file/ftp URLs go through fetch().
    if (/^[a-z]+:\/\//i.test(source)) {
      const response = await fetch(source);
      if (!response.ok) {
        throw new Error(`Failed to fetch ${source}: ${response.status} ${response.statusText}`);
      }
      return new Uint8Array(await response.arrayBuffer());
    }
    // 3) Anything else that looks like a base64 string is decoded directly.
    //    This is the format `boxpdf font add` emits and the format
    //    `boxpdf/inter` re-exports its bundled Inter weights in.
    if (/^[A-Za-z0-9+/=\s]+$/.test(source)) {
      return decodeBase64(source);
    }
    throw new Error(
      "Unrecognized asset source string. Pass a URL (http://, https://, data:), a base64 string, or a Uint8Array."
    );
  }
  throw new Error("Unsupported asset source — expected string URL/data URL/base64, Uint8Array, or ArrayBuffer.");
}

function decodeBase64(input: string): Uint8Array {
  const clean = input.replace(/\s+/g, "");
  if (typeof atob === "function") {
    const binary = atob(clean);
    const out = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
    return out;
  }
  // Node fallback — `Buffer` is global in Node.
  const buf = (globalThis as { Buffer?: { from: (data: string, encoding: string) => { buffer: ArrayBuffer; byteOffset: number; byteLength: number } } }).Buffer;
  if (buf) {
    const b = buf.from(clean, "base64");
    return new Uint8Array(b.buffer, b.byteOffset, b.byteLength);
  }
  throw new Error("No base64 decoder available in this runtime.");
}

/**
 * Embed an image into the PDF, auto-detecting PNG vs JPEG from magic bytes.
 * Accepts an HTTP URL, a `data:image/...` URL, a base64 string, raw bytes,
 * or an ArrayBuffer.
 *
 * @example
 *   const logo = await loadImage(pdf, "https://example.com/logo.png");
 *   const headshot = await loadImage(pdf, fs.readFileSync("./headshot.jpg"));
 *   image(logo, { width: 120, height: 40 });
 */
export async function loadImage(pdf: PDFDocument, source: AssetSource): Promise<PDFImage> {
  const bytes = await readSource(source);
  if (bytesStartWith(bytes, PNG_MAGIC)) return pdf.embedPng(bytes);
  if (bytesStartWith(bytes, JPEG_MAGIC)) return pdf.embedJpg(bytes);
  throw new Error("loadImage: unsupported format — only PNG and JPEG are recognized.");
}

export interface LoadFontOptions {
  /** Subset the font down to the glyphs the document actually uses. Default true. */
  subset?: boolean;
  /** OpenType feature toggles (e.g., `{ tnum: true }` for tabular numerals). */
  features?: Record<string, boolean>;
}

/**
 * Load a TTF/OTF font into the PDF. Accepts any of:
 *
 *   - `Uint8Array` / `ArrayBuffer` — raw bytes.
 *   - `string` starting with `http://` or `https://` — fetched at runtime.
 *   - `string` starting with `data:` — parsed as a data URL.
 *   - `string` matching the base64 alphabet — decoded directly. This is the
 *     shape generated by `npx boxpdf font add` and re-exported from
 *     `boxpdf/inter`.
 *
 * Registers `@pdf-lib/fontkit` on the document automatically (lazy-loaded
 * the first time `loadFont` is called).
 *
 * @example
 *   import { loadFont } from "boxpdf";
 *   import { inter, interBold } from "boxpdf/inter";
 *
 *   const font  = await loadFont(pdf, inter);
 *   const bold  = await loadFont(pdf, interBold);
 *   const tabBold = await loadFont(pdf, interBold, { features: { tnum: true } });
 *
 *   // Or from a URL on an edge runtime where the asset is cache-friendly:
 *   const brand = await loadFont(pdf, "https://example.com/Acme-Regular.ttf");
 */
export async function loadFont(
  pdf: PDFDocument,
  source: AssetSource,
  options: LoadFontOptions = {}
): Promise<PDFFont> {
  const bytes = await readSource(source);
  // Custom fonts require fontkit; dynamic-imported so it only loads when this
  // helper is actually called (keeps the core bundle slim for users who only
  // use the built-in StandardFonts).
  const fontkitMod = (await import("@pdf-lib/fontkit")) as unknown as { default?: unknown };
  const fontkit = fontkitMod.default ?? fontkitMod;
  pdf.registerFontkit(fontkit as Parameters<typeof pdf.registerFontkit>[0]);
  return pdf.embedFont(bytes, { subset: options.subset ?? true, features: options.features });
}

/**
 * @deprecated since 1.1.0 — use {@link loadFont}. `embedFont(pdf, { source })`
 * remains as a backwards-compatible alias and will be removed in a future
 * major release.
 */
export async function embedFont(
  pdf: PDFDocument,
  options: { source: AssetSource; subset?: boolean }
): Promise<PDFFont> {
  return loadFont(pdf, options.source, { subset: options.subset });
}
